image: jojomi/hugo:latest@sha256:cfc23010cde7a5af05794435e4d56a9fb70fff4bf7087835f749d72c3e3ab09b

variables:
  HUGO_DESTINATION: public

pages:
  artifacts:
    paths:
      - public/
  only:
    - master
  script:
    - hugo --minify
