image: jojomi/hugo:latest@sha256:acf0a58f726c51b450f3393c0140f1bc13b1e4be0c864ca278fd5ad4ffe17e4e

variables:
  HUGO_DESTINATION: public

pages:
  artifacts:
    paths:
      - public/
  only:
    - master
  script:
    - hugo
